image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache py3-pip
  - apk add --no-cache docker-compose
  - echo "ENV_VARIABLE=value" > .env  # Добавьте эту строку для создания файла .env

build:
  stage: build
  script:
    - git pull git@62.217.183.24:ai-sdr-agent/ai-sdr-agent.git
    - docker-compose build

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d