image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]  # Keep DinD running

variables:
  DOCKER_HOST: tcp://docker:2375  # Use TCP for Docker
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker
  DOCKER_DRIVER: overlay2  # Use overlay2 as the storage driver

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache py3-pip docker-compose git
  - echo "ENV_VARIABLE=value" > .env  # Create .env file

build:
  stage: build
  script:
    - cd /builds/ai-sdr-agent  # Navigate to the project directory
    - git pull origin main  # Pull latest changes from the repository
    - docker-compose build  # Build containers using Docker Compose

deploy:
  stage: deploy
  script:
    - cd /builds/ai-sdr-agent  # Navigate to the project directory
    - docker-compose down  # Stop old containers
    - docker-compose up -d  # Start new containers in detached mode
  only:
    - main  # This stage runs only for the main branch