stages:
  - deploy

deploy:
  stage: deploy
  script:
    #- "Переходим в каталог /home/gitlab-runner/ai-sdr-agent"
    - git config --global --add safe.directory /home/gitlab-runner/ai-sdr-agent
    - cd /home/gitlab-runner/ai-sdr-agent
    - echo "Выполняем git pull"
    - git pull || { echo "Не удалось выполнить git pull"; exit 1; }
    - echo "Останавливаем контейнеры"
    - docker-compose down || { echo "Не удалось остановить контейнеры"; exit 1; }
    - echo "Запускаем контейнеры с пересборкой"
    - docker-compose up -d --build || { echo "Не удалось запустить контейнеры"; exit 1; }
  only:
    - main  # №Замените на вашу ветку, если нужно