image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache py3-pip
  - apk add --no-cache docker-compose
  - apk add --no-cache git
  - echo "ENV_VARIABLE=value" > .env

build:
  stage: build
  script:
    - if [ ! -d "/builds/ai-sdr-agent/.git" ]; then git clone http://62.217.183.24/ai-sdr-agent/ai-sdr-agent.git /builds/ai-sdr-agent; elif [ -d "/builds/ai-sdr-agent/.git" ]; then git -C /builds/ai-sdr-agent pull origin main; else echo "Directory exists but is not a git repository."; exit 1; fi

deploy:
  stage: deploy
  script:
    - cd /builds/ai-sdr-agent
    - docker-compose down
    - docker-compose up -d
  only:
    - main