image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]  # Переопределяем точку входа для DinD

variables:
  DOCKER_HOST: unix:///var/run/docker.sock  # Используем сокет Docker на хосте
  DOCKER_TLS_CERTDIR: ""  # Отключаем TLS для Docker

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache py3-pip
  - apk add --no-cache docker-compose
  - apk add --no-cache git
  - echo "ENV_VARIABLE=value" > .env  # Создание файла .env

build:
  stage: build
  script:
    - git pull origin main  # Выполнение git pull из репозитория
    - docker-compose build  # Строим контейнеры с помощью Docker Compose

deploy:
  stage: deploy
  script:
    - docker-compose down  # Останавливаем старые контейнеры
    - docker-compose up -d  # Запускаем новые контейнеры в фоновом режиме
  only:
    - main  # Эта стадия выполняется только для ветки main
