image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache py3-pip
  - apk add --no-cache docker-compose
  - apk add --no-cache git
  - echo "ENV_VARIABLE=value" > .env  # Создание файла .env

build:
  stage: build
  script:
    - cd /builds/ai-sdr-agent  # Переход в каталог внутри контейнера
    - git pull origin main  # Выполнение git pull из локального репозитория
    - docker-compose build

volumes:
  - /root/ai-sdr-agent:/builds/ai-sdr-agent  # Монтирование существующего каталога

deploy:
  stage: deploy
  script:
    - cd /builds/ai-sdr-agent  # Переход в каталог внутри контейнера
    - docker-compose down
    - docker-compose up -d

volumes:
  - /root/ai-sdr-agent:/builds/ai-sdr-agent  # Монтирование существующего каталога