image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Переходим в каталог /root/ai-sdr-agent"
    - cd /root/ai-sdr-agent
    - echo "Выполняем git pull"
    - git pull || { echo "Не удалось выполнить git pull"; exit 1; }
    - echo "Останавливаем контейнеры"
    - docker-compose down
    - echo "Запускаем контейнеры с пересборкой"
    - docker-compose up -d --build
  only:
    - main  # Замените на вашу ветку, если нужно