stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Переходим в каталог /root/ai-sdr-agent"
    - cd /root/ai-sdr-agent
    - echo "Выполняем git pull"
    - git pull || { echo "Не удалось выполнить git pull"; exit 1; }
    - echo "Останавливаем контейнеры"
    - docker-compose down || { echo "Не удалось остановить контейнеры"; exit 1; }
    - echo "Запускаем контейнеры с пересборкой"
    - docker-compose up -d --build || { echo "Не удалось запустить контейнеры"; exit 1; }
  only:
    - main  # Замените на вашу ветку, если нужно